source_type: CB4_64_16D_STK_v1
output_type: CB4_64_16D_STK_v1_ingested

description: CBERS-4 ingested data

location: '/data/ingested/'
file_path_template: 'CB4_64_16D_STK_v1_ingested/CB4_64_16D_STK_v1_ingested_{tile_index[0]}_{tile_index[1]}_{start_time}.nc'

global_attributes:
    title: CBERS 4 ingested
    summary: CBERS-4 data product
    source: CBERS 4 version 1
    institution: INPE
    instrument: AWFI
    cdm_data_type: Grid
    keywords: REFLECTANCE,CBERS,EARTH SCIENCE
    platform: CBERS-4
    processing_level: L2
    product_version: '1.0'
    product_suite: INPE CBERS4
    project: BDC
    naming_authority: bdc.inpe
    acknowledgment: CBERS4 is provided by the National Institute for Space Research (INPE).

storage:
    driver: NetCDF CF

    crs: +proj=aea +lat_0=-12 +lon_0=-54 +lat_1=-2 +lat_2=-22 +x_0=5000000 +y_0=10000000 +ellps=GRS80 +units=m +no_defs
    tile_size:
            x: 100000.0
            y: 100000.0
    resolution:
            x: 64
            y: -64
    chunking:
        x: 200
        y: 200
        time: 1
    dimension_order: ['time', 'y', 'x']

measurements:
    - name: blue
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'blue'
      zlib: True
      attrs:
        long_name: "BAND13"
        alias: "BAND13"

    - name: evi
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'evi'
      zlib: True
      attrs:
        long_name: "EVI"
        alias: "EVI"

    - name: green
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'evi'
      zlib: True
      attrs:
        long_name: "BAND14"
        alias: "BAND14"

    - name: ndvi
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'ndvi'
      zlib: True
      attrs:
        long_name: "BAND16"
        alias: "BAND16"

    - name: red
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'red'
      zlib: True
      attrs:
        long_name: "BAND15"
        alias: "BAND15"
